# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xprns_api', '0002_bucketlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlistitem',
            name='bucketlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xprns_api.Bucketlist'),
            preserve_default=False,
        ),
    ]
